set -g mouse on
bind -n M-1 select-pane -t 1
bind -n M-2 select-pane -t 2
bind -n M-3 select-pane -t 3
set -sg escape-time 0
set -g history-limit 10000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
